### ISSUE TITLE
Add java solution for shifted array search

### ISSUE THREAD

**Issue by Swathi-L** [arin2002/Coding-questions#117]
Problem description:
There is an integer array nums sorted in ascending order (with distinct values).

Prior to being passed to your function, nums is possibly rotated at an unknown pivot index k (1 <= k < nums.length) such that the resulting array is [nums[k], nums[k+1], ..., nums[n-1], nums[0], nums[1], ..., nums[k-1]] (0-indexed). For example, [0,1,2,4,5,6,7] might be rotated at pivot index 3 and become [4,5,6,7,0,1,2].

Given the array nums after the possible rotation and an integer target, return the index of target if it is in nums, or -1 if it is not in nums.

You must write an algorithm with O(log n) runtime complexity.

**Comment by Swathi-L** [comment]
I am ready to work on this, please assign it to me

**Comment by arin2002** [comment]
ok

**Comment by akshay10k** [comment]
please assign it to me.

**Comment by arin2002** [comment]
ok @akshay10k
