### ISSUE TITLE
Add C programs in C folder 

### ISSUE THREAD

**Issue by KrunalGupta02** [arin2002/Coding-questions#469]
Hi, I want to add the Beginner C programs for the community can anyone  plz assign me this task

**Comment by arin2002** [comment]
ok @KrunalGupta02

**Comment by KrunalGupta02** [comment]
Done kindly add the hacktoberfest label

**Comment by Anirban6756** [comment]
Hii i'm new to all this but i have some coding knowledge.....i know C programming language.....can you assign me some task so that i can avail this hacktober event :)

**Comment by arin2002** [comment]
@Anirban6756 dont ask for assignes just pull request with issue number dont forget to put hashtag it wull work well

**Comment by Anirban6756** [comment]
Thankyou very much @arin2002....can you just tell me what i have to do rest i will manage....and again sorry for the inconvenience :)

**Comment by arin2002** [comment]
just add C program in C folder @Anirban6756

**Comment by KrunalGupta02** [comment]
@Anirban6756  kindly close this issue
