### ISSUE TITLE
add dsa solutions in your language folder

### ISSUE THREAD

**Issue by arin2002** [arin2002/Coding-questions#80]
Dont ask for assignes just mention the issue number and push your request this will also work

**Comment by Hussain6** [comment]
I have pulled the repo with Heap Sort with Max Heapify in cpp program PR#94

**Comment by jayantchaudhari18** [comment]
Hey @arin2002 can you please assign me.

**Comment by arin2002** [comment]
@jayantchaudhari18 well there is no need of assignment just mention the issue with PR it will work

**Comment by Hussain6** [comment]
@arin2002 i have already pulled the repo its merge but the labels are not assigned can you please assign them.

**Comment by arin2002** [comment]
@Hussain6  it will done itself dont worry

**Comment by Hussain6** [comment]
@arin2002 Ok

**Comment by bhavyagupta-11** [comment]
Hey even I want to contribute. Kindly assign this to me

**Comment by arin2002** [comment]
go on @bhavyagupta-11

**Comment by extasyhere** [comment]
Hey even I want to contribute. Kindly assign this to me

**Comment by deepesh16b** [comment]
Hi @Hussain6 
Please assign this to me

**Comment by deepesh16b** [comment]
Hi @Hussain6 
Please assign this to me

**Comment by deepesh85b** [comment]
@arin2002 
Please assign this to me

**Comment by aniket-varma** [comment]
Please Assign me this task

**Comment by 889-dj** [comment]
hey @arin2002 i also wanted to work on this can u assign me this

**Comment by arin2002** [comment]
ok @889-dj
